### ISSUE TITLE
2 ways binding on Input text

### ISSUE THREAD

**Issue by ferchoman09** [krescruz/angular-materialize#120]
When angular set a value to input text from javascript since control scope change, the input text don't add the class 'valid'. The label should use too the 'active' class for proper operation.

**Comment by webbiesdk** [comment]
Sorry, I simple don't get what it is you are trying to say should happen.

**Comment by saravanakumarputta** [comment]
I have a problem, that i have given ng-model="data" to textbox and trying to access it from controllore as  var data1=$scope.data; an getting undefined, can anyone please suggest the solution.

**Comment by webbiesdk** [comment]
Okay, for both of these of these I need some more info. 

Make an example on a site like JSFiddle. You can use this as a starting point: http://jsfiddle.net/Lvc0u55v/4071/

@Saravana-Kumar-putta That goes for you too. And how does your issue have anything to do with the original issue? 
(Your issue might be because you havn't initialized $scope.data in your controller)

This is closed until example is given.
