### ISSUE TITLE
Throw Toast from controller

### ISSUE THREAD

**Issue by simon-tannai** [krescruz/angular-materialize#140]
Hi !

I would like to know if there is some way to throw a toast from a controller ?

In Materialize CSS documentation, they said that we must use this function:
`Materialize.toast('I am a toast!', 4000)`

But in my controller, "Materialize" doesn't exists.

**Comment by webbiesdk** [comment]
Are you sure you've included Materialize.js

Because the way the toast directive works, is that it calls Materialize.toast(...)
So you should also be able to just call Materialize.toast(...)

**Comment by simon-tannai** [comment]
Yes I have included materialize.js:

```
<script src="bower_components/materialize/bin/materialize.js"></script>
<script src="bower_components/angular-materialize/src/angular-materialize.js"></script>
```

**Comment by webbiesdk** [comment]
Then I don't know what is happening, but I still think it is some setup on your end, because I can run `Materialize.toast('I am a toast!', 4000)` just fine on http://krescruz.github.io/angular-materialize/. (Just open the console and type it in). 

This means that we cannot help you any further unless you provide more information, preferably in the form of a link to a page where the issue is present (you can just use JSFiddle or similar).

**Comment by webbiesdk** [comment]
I consider this issue done closed, the functionality works just fine on the demo page.
