### ISSUE TITLE
Input field directive returns undefined object

### ISSUE THREAD

**Issue by johhansantana** [krescruz/angular-materialize#145]
I'm using your `input-field` directive.

here's my html markup:

``` html
<form>
  <div input-field class="input-field col s12">
    <input type="email" id="email" ng-model="email" name="email" length="50" maxlength="50" required>
    <label for="email">Email</label>
  </div>
  <div class="col s12">
    <a class="btn-floating btn waves-effect waves-light"
     id="addEmail"
     type="submit"
     ng-click="addEmail(email)">
     <i class="material-icons">add</i>
   </a>
  </div>
</form>
```

and here's the controller:

``` javascript
$scope.emailList = [];

$scope.addEmail = function (email) {
  console.log(email);
  $scope.emailList.push(email);
  console.log($scope.emailList);
}
```

when I press the `addEmail` button function, the console logs `undefined` but if I take out the `input-field` directive, it works fine.

I've tried like `<input-field></input-field>` and with `<div input-field></div>` but no luck.

**Comment by webbiesdk** [comment]
Can confirm, its the `type="email"` that somehow screws things up. 

If you want to work for now, you can just put in `type="text"` instead, the only thing you'll miss is the input-validation.

**Comment by webbiesdk** [comment]
Ok, I got it to work. 

Se this: http://stackoverflow.com/questions/17606936/angularjs-dot-in-ng-model

So its not directly the fault of the `input-field` directive, its because of scoping and how Angular is designed. 

You just have to put your email inside an object of some sort, you could as an example just put an empty object on the scope: `$scope.inputs = {}`.
