### ISSUE TITLE
select dropdown with checkboxes does not attach ng-model with them

### ISSUE THREAD

**Issue by crisryantan** [krescruz/angular-materialize#147]
I think this is not yet implemented yet

**Comment by webbiesdk** [comment]
Ehh, gonna need some more information here. 

Because when you say. "select dropbox with checkboxes", i think the "multiple" example that can be seen here: 
http://krescruz.github.io/angular-materialize/#select

And ng-model works fine with that, as you can see in the example. 

This issue is closed until you link to a page (like JSFiddle or whatever), that shows something that is supposed to work, that doesn't work.

**Comment by crisryantan** [comment]
My bad on that one man, was using an older version of angular-materialize and forgot to check the new one. I'm Sorry!
