### ISSUE TITLE
Pagination causing flashing

### ISSUE THREAD

**Issue by shubh3794** [krescruz/angular-materialize#150]
Hello, I recently installed this plugin and I am including the script at the bottom of my body and I am able to use Pagination directive but on changing the page, it is causing flashing of whole of the paginator. How to get around this.

**Comment by webbiesdk** [comment]
When i try our demo implemetation of Pagination: http://krescruz.github.io/angular-materialize/#pagination I cannot reproduce the behaviour you are describing. 

Please post a link to a site where the issue is visible (you could create the example on a page like JSFiddle or similar). 

Closed until the issue is reproducible.
