### ISSUE TITLE
How to use protractor to select dropdown box

### ISSUE THREAD

**Issue by dhaval85** [krescruz/angular-materialize#176]
I am unable to use the standard protractor tags e.g by.modal with angular materialize selection box. Any one tried this or know the solution?

**Comment by webbiesdk** [comment]
The materialize selection box does some funny buisness, because the floating "select" that you click on when using material-select is actually a clone of the content in the select. The select is hidden in the background. 

So if you want to have protractor select something, you have to really look into how the DOM structure is after it has initialized.

**Comment by dhaval85** [comment]
@webbiesdk Thanks! The issue is solved the same way you mentioned.
