### ISSUE TITLE
Issue with Collapsible

### ISSUE THREAD

**Issue by dinolunch** [krescruz/angular-materialize#36]
Love what you are doing with materialize! Just ran into one issue.  When working with the collapsible if the scope changes the collapse functionality stops working.  For example if I have a scope that has an array in it, if I have a function that removes one item from the array, the collapse functionality stops working.  Might be user error on my side, just let me know.

Thanks!

**Comment by webbiesdk** [comment]
As has been written to some of the others, if you could give a link, a JSfiddle or a zip-file that demonstrates the problem. Then it would be easier to figure out the problem.

**Comment by marcobaldo** [comment]
@webbiesdk here is a jsfiddle demonstrating a similar issue https://jsfiddle.net/xfjg3pg0/

Wait for the data to load. The bottom two items are hardcoded HTML while the top items are from the ng-repeat. If the ng-repeat data is from an $http or $resource call, clicking on it does not work. On the console, I see a lot of element.collapsible is not a function

The same data when hardcoded instead of being loaded over the internet produces the desired/correct result.

**Comment by webbiesdk** [comment]
@marcobaldo I think you need to fix that link, this is what I'm seeing. 
http://i.imgur.com/vBjItPY.png

**Comment by marcobaldo** [comment]
Sorry about that, @webbiesdk. I missed the update button. Here you go https://jsfiddle.net/xfjg3pg0/3/

**Comment by elboman** [comment]
The reason why it doesn't work is because data is loaded asyncronously. The directive just compiles what's in it and triggers the materialize js. Basically is a poor implementation. We can rewrite the directive  to recive the collapsible data and then watch for changes to retrigger the code.. Let me try something and I'll get back to you later..

**Comment by marcobaldo** [comment]
Thanks. For now, I'm using ui-router's resolve so I don't experience this issue.

**Comment by webbiesdk** [comment]
Okay, i found i way to fix it, but it is heavy on computation, so I haven't enabled it as the default. 

But with the above commit, if you add the attribute `watch`, then the collapsible will re-initialize whenever some content within it changes. 

I have tested it, and it fixes this issue.
