### ISSUE TITLE
Textarea not updating height

### ISSUE THREAD

**Issue by cskiwi** [krescruz/angular-materialize#72]
Hi,

When you have initial data for your text-area it doesn't set the auto height, is there a way to manual trigger it or a sollution?

the problem is illustrated here: http://plnkr.co/edit/zd2hV4xaCoyhFKDvzGAX?p=preview
do any update in the text-area and then it updates the height

**Comment by webbiesdk** [comment]
Right you are, and that issue can easily be fixed by triggering "autoresize" when the directive runs, as done here: 
http://plnkr.co/edit/faqb6RunajeZ65uyMbTu?p=preview
(Look in angular-materialize at the inputField directive)

But there is a more serious related issue, that changing the value of the model, does not update the height of the text-field. I'm working on that now.

**Comment by webbiesdk** [comment]
The "mega" commit above fixes your issue, and also the issue i mentioned about changes to the model not changing the height of textareas.
